'use strict';

exports.__esModule = true;
exports.default = {
  'Add': ['create', 'core', 'increase', 'increment', 'new', 'plus'],
  'Amazon': ['buy', 'marketplace', 'online', 'shopping', 'social'],
  'AmericanExpress': ['atm', 'card', 'credit', 'pay', 'wallet', 'social'],
  'Bitcoin': ['coin', 'currency', 'finance', 'social', 'pay', 'money', 'wallet'],
  'CarrotDown': ['arrow', 'core', 'direction', 'down', 'expand', 'up'],
  'CarrotUp': ['arrow', 'collapse', 'core', 'direction', 'down', 'up'],
  'Chat': ['bubble', 'communication', 'core', 'help', 'message', 'talk', 'support'],
  'Checkmark': ['accept', 'agree', 'core', 'done', 'good', 'ok'],
  'Close': ['cancel', 'core', 'delete', 'escape', 'exit', 'remove', 'trash'],
  'Codepen': ['codepen.io', 'code', 'demo', 'logo', 'media', 'share', 'social'],
  'Configure': ['core', 'preferences', 'setting', 'settings', 'tool', 'wrench'],
  'CreativeCommons': ['creative commons', 'license', 'social'],
  'Document': ['core', 'file', 'format', 'folder', 'page', 'paper'],
  'Download': ['arrow', 'cloud', 'core', 'import', 'get', 'receive'],
  'Dropbox': ['box', 'cloud', 'logo', 'media', 'share', 'social'],
  'Edit': ['change', 'core', 'draw', 'modify', 'pen', 'pencil', 'write'],
  'Facebook': ['share', 'logo', 'media', 'network', 'social'],
  'FacebookOption': ['share', 'logo', 'media', 'network', 'social'],
  'Filter': ['core', 'funnel', 'refine', 'sort', 'triage'],
  'Flag': ['core', 'nation', 'warn', 'warning'],
  'FormAdd': ['create', 'form', 'increase', 'increment', 'new', 'plus'],
  'formAttachment': ['attach', 'clip', 'file', 'form', 'paper', 'upload'],
  'FormCalendar': ['date', 'day', 'event', 'form', 'month', 'schedule', 'year'],
  'FormClock': ['alarm', 'form', 'hour', 'minute', 'second', 'time', 'timer', 'watch'],
  'FormClose': ['cancel', 'close', 'delete', 'escape', 'exit', 'form', 'remove', 'trash'],
  'FormCheckmark': ['accept', 'agree', 'done', 'form', 'good', 'ok'],
  'FormCut': ['scissor', 'scissor', 'form', 'tool'],
  'FormDown': ['arrow', 'direction', 'form', 'down', 'expand', 'up'],
  'FormFilter': ['form', 'funnel', 'refine', 'sort', 'triage'],
  'FormFolder': ['file', 'files', 'document', 'form', 'organize'],
  'FormLocation': ['directions', 'form', 'gps', 'map', 'navigation', 'pin'],
  'FormLock': ['form', 'locker', 'password', 'permissions', 'protect', 'secure', 'security'],
  'FormNext': ['arrow', 'direction', 'form', 'forward', 'next', 'right'],
  'FormNextLink': ['arrow', 'direction', 'form', 'forward', 'next', 'right'],
  'FormPrevious': ['arrow', 'back', 'backward', 'direction', 'form', 'left', 'return'],
  'FormPreviousLink': ['arrow', 'back', 'backward', 'direction', 'form', 'left', 'return'],
  'FormRefresh': ['arrow', 'form', 'pull', 'reload', 'sync', 'update'],
  'FormSearch': ['find', 'form', 'lookup', 'magnifier', 'search'],
  'FormSchedule': ['appointment', 'calendar', 'date', 'event', 'form', 'meeting', 'time'],
  'FormSubtract': ['decrement', 'delete', 'form', 'minus', 'reduce', 'remove'],
  'FormTrash': ['bin', 'clear', 'core', 'delete', 'eliminate', 'escape', 'form', 'garbage', 'remove'],
  'FormUp': ['arrow', 'direction', 'collapse', 'form', 'up'],
  'FormUpload': ['arrow', 'attach', 'attachment', 'cloud', 'export', 'file', 'form', 'send'],
  'FormView': ['eye', 'form', 'open'],
  'FormViewHide': ['close', 'eye', 'form'],
  'Github': ['code', 'demo', 'logo', 'media', 'share', 'social', 'opensource'],
  'GooglePlus': ['logo', 'media', 'share', 'social'],
  'GoogleWallet': ['logo', 'media', 'online', 'pay', 'social', 'transaction', 'wallet'],
  'Instagram': ['camera', 'image', 'logo', 'media', 'picture', 'photo', 'share', 'social', 'video'],
  'Linkedin': ['logo', 'network', 'media', 'share', 'social'],
  'LinkedinOption': ['logo', 'network', 'media', 'share', 'social'],
  'LinkNext': ['arrow', 'core', 'direction', 'forward', 'next', 'right'],
  'LinkPrevious': ['arrow', 'back', 'backward', 'core', 'direction', 'left', 'return'],
  'Mail': ['email', 'envelope', 'letter', 'message', 'social'],
  'Mastercard': ['card', 'credit', 'logo', 'pay', 'wallet', 'social', 'visa'],
  'Medium': ['blog', 'logo', 'media', 'share', 'social'],
  'More': ['actions', 'core', 'ellipses'],
  'Next': ['arrow', 'core', 'direction', 'forward', 'next', 'right'],
  'Notification': ['alarm', 'alert', 'bell', 'core', 'message', 'notify', 'warn', 'warning'],
  'Paypal': ['card', 'logo', 'media', 'money', 'social', 'pay', 'wallet'],
  'Pinterest': ['logo', 'media', 'share', 'social'],
  'Previous': ['arrow', 'back', 'backward', 'core', 'direction', 'left', 'return'],
  'Product-hunt': ['logo', 'media', 'share', 'social'],
  'Reddit': ['logo', 'media', 'online', 'social', 'share'],
  'Refresh': ['arrow', 'core', 'reload', 'pull', 'sync', 'update'],
  'Search': ['core', 'find', 'lookup', 'magnifier', 'zoom'],
  'Share': ['connections', 'score', 'open', 'network', 'publish'],
  'Skype': ['call', 'chat', 'conference', 'logo', 'media', 'phone', 'social', 'video'],
  'Slack': ['chat', 'help', 'logo', 'media', 'message', 'talk', 'share', 'social', 'support'],
  'Snapchat': ['ghost', 'image', 'logo', 'media', 'picture', 'photo', 'share', 'social', 'video'],
  'Square': ['logo', 'media', 'social', 'pay', 'wallet'],
  'StackOverflow': ['code', 'help', 'logo', 'media', 'share', 'social'],
  'Stripe': ['logo', 'media', 'pay', 'social', 'wallet'],
  'Subtract': ['core', 'decrement', 'minus', 'reduce'],
  'Twitter': ['bird', 'logo', 'media', 'share', 'social', 'tweet'],
  'Trash': ['bin', 'clear', 'core', 'delete', 'eliminate', 'escape', 'garbage', 'remove'],
  'Tumblr': ['blog', 'image', 'logo', 'media', 'picture', 'photo', 'share', 'social', 'video'],
  'Update': ['arrow', 'change', 'core', 'reload', 'refresh'],
  'Upload': ['arrow', 'attach', 'attachment', 'cloud', 'core', 'export', 'file', 'send'],
  'User': ['account', 'avatar', 'core', 'person', 'profile'],
  'Vimeo': ['logo', 'media', 'share', 'social', 'video'],
  'Visa': ['card', 'mastercard', 'media', 'pay', 'social', 'wallet'],
  'Youtube': ['logo', 'media', 'play', 'share', 'social', 'video'],
  'Wordpress': ['blog', 'logo', 'media', 'share', 'social']
};