'use strict';

exports.__esModule = true;
exports.default = {
  'add': ['create', 'core', 'increase', 'increment', 'plus'],
  'amazon': ['buy', 'marketplace', 'social'],
  'american-express': ['card', 'pay', 'wallet', 'social'],
  'bitcoin': ['social', 'pay', 'wallet'],
  'carrot-down': ['core', 'down', 'expand'],
  'carrot-up': ['collapse', 'core', 'up'],
  'chat': ['core', 'help', 'message', 'talk', 'support'],
  'checkmark': ['accept', 'agree', 'core', 'good', 'ok'],
  'close': ['core', 'delete', 'escape', 'remove', 'trash'],
  'codepen': ['code', 'demo', 'share', 'social'],
  'configure': ['core', 'preferences', 'settings', 'tool'],
  'creative-commons': ['license', 'social'],
  'document': ['core', 'file', 'page'],
  'download': ['core', 'import', 'get', 'receive'],
  'dropbox': ['cloud', 'share', 'social'],
  'edit': ['change', 'core', 'draw', 'modify', 'pencil'],
  'facebook': ['share', 'social'],
  'facebook-option': ['share', 'social'],
  'filter': ['core', 'funnel', 'refine', 'triage'],
  'flag': ['core', 'warn', 'warning'],
  'form-add': ['create', 'form', 'increase', 'increment', 'plus'],
  'form-attachment': ['attach', 'clip', 'form', 'upload'],
  'form-calendar': ['date', 'day', 'form', 'month', 'year'],
  'form-clock': ['form', 'hour', 'minute', 'second', 'time', 'watch'],
  'form-close': ['close', 'delete', 'escape', 'form', 'remove', 'trash'],
  'form-checkmark': ['accept', 'agree', 'form', 'good', 'ok'],
  'form-cut': ['cisors', 'form'],
  'form-dowm': ['form', 'down', 'expand'],
  'form-filter': ['form', 'funnel', 'refine', 'triage'],
  'form-folder': ['form', 'organize'],
  'form-location': ['directions', 'form', 'pin'],
  'form-lock': ['form', 'locker', 'permissions', 'protect', 'secure'],
  'form-next': ['form', 'forward', 'next', 'right'],
  'form-previous': ['back', 'backward', 'form', 'left', 'return'],
  'form-previous-link': ['back', 'backward', 'form', 'left', 'return'],
  'form-refresh': ['form', 'pull', 'update'],
  'form-search': ['find', 'form', 'lookup', 'magnifier', 'search'],
  'form-schedule': ['appointment', 'form', 'meeting'],
  'form-subtract': ['decrement', 'form', 'menus', 'reduce'],
  'form-trash': ['clear', 'core', 'delete', 'eliminate', 'escape', 'form', 'remove'],
  'form-up': ['collapse', 'form', 'up'],
  'form-upload': ['attach', 'attachment', 'export', 'form', 'send'],
  'form-view': ['eye', 'form', 'open'],
  'form-view-hide': ['close', 'eye', 'form'],
  'github': ['code', 'demo', 'share', 'social', 'opensource'],
  'google-plus': ['share', 'social'],
  'google-wallet': ['social', 'pay', 'wallet'],
  'instagram': ['image', 'picture', 'photo', 'share', 'social', 'video'],
  'linkedin': ['share', 'social'],
  'linkedin-option': ['share', 'social'],
  'link-next': ['arrow', 'core', 'forward', 'next', 'right'],
  'link-previous': ['arrow', 'back', 'backward', 'core', 'left', 'return'],
  'mail': ['email', 'message', 'social'],
  'mastercard': ['card', 'pay', 'wallet', 'social'],
  'medium': ['blog', 'share', 'social'],
  'more': ['actions', 'core'],
  'next': ['core', 'forward', 'next', 'right'],
  'notification': ['alert', 'bell', 'core', 'notify', 'warn', 'warning'],
  'paypal': ['social', 'pay', 'wallet'],
  'pinterest': ['share', 'social'],
  'previous': ['back', 'backward', 'core', 'left', 'return'],
  'product-hunt': ['share', 'social'],
  'reddit': ['social', 'share'],
  'refresh': ['core', 'pull', 'update'],
  'search': ['core', 'find', 'lookup', 'magnifier'],
  'share': ['core', 'open', 'publish'],
  'skype': ['call', 'conference', 'phone', 'social', 'video'],
  'slack': ['chat', 'help', 'message', 'talk', 'share', 'social', 'support'],
  'snapchat': ['image', 'picture', 'photo', 'share', 'social', 'video'],
  'square': ['social', 'pay', 'wallet'],
  'stack-overflow': ['code', 'help', 'share', 'social'],
  'stripe': ['social', 'pay', 'wallet'],
  'subtract': ['core', 'decrement', 'minus', 'reduce'],
  'twitter': ['share', 'social', 'tweet'],
  'trash': ['clear', 'core', 'delete', 'eliminate', 'escape', 'remove'],
  'tumblr': ['blog', 'image', 'picture', 'photo', 'share', 'social', 'video'],
  'update': ['change', 'core'],
  'upload': ['attach', 'attachment', 'core', 'export', 'send'],
  'user': ['core', 'person', 'profile'],
  'vimeo': ['share', 'social', 'video'],
  'visa': ['card', 'pay', 'wallet', 'social'],
  'youtube': ['share', 'social', 'video'],
  'wordpress': ['blog', 'share', 'social']
};