export default {
  'Accessibility': ['body', 'disabled', 'disability', 'human'],
  'Achievement': ['award', 'medal', 'prize', 'winner'],
  'Action': ['connect', 'plug'],
  'Actions': ['gear', 'sun'],
  'Ad': ['advertising', 'marketing', 'promotion'],
  'Add': ['create', 'core', 'increase', 'increment', 'new', 'plus'],
  'AddCircle': ['create', 'increase', 'increment', 'new', 'plus'],
  'Aed': ['cpr', 'defibrillator', 'emergency', 'heart', 'medical', 'shock'],
  'Aggregate': ['add', 'combinatin', 'combine', 'join', 'merge'],
  'Aid': ['briefcase', 'care', 'first-aid', 'first aid kit', 'health', 'hospital'],
  'AidOption': ['briefcase', 'care', 'first-aid', 'first aid kit', 'health', 'hospital'],
  'Alarm': ['alert', 'alarmclock', 'bell', 'clock', 'time', 'timer'],
  'Alert': ['alarm', 'attention', 'error', 'important', 'warning'],
  'Amazon': ['buy', 'marketplace', 'online', 'shopping', 'social'],
  'Amex': ['atm', 'card', 'credit', 'pay', 'wallet', 'social'],
  'Analytics': ['chart', 'diagram', 'dontusepies', 'graph', 'pie', 'report', 'statistics'],
  'Android': ['cyborg', 'droid', 'humanoid', 'mobile', 'os', 'phone', 'robot', 'smartphone'],
  'Announce': ['bullhorn', 'loud', 'speaker', 'megaphone'],
  'Apple': ['donglebook', 'iphone', 'imac', 'logo', 'mac', 'macbook'],
  'Archive': ['box', 'container', 'document', 'file', 'folder', 'storage'],
  'Archlinux': ['linux', 'logo', 'os'],
  'Article': ['blog', 'news', 'newspaper', 'press'],
  'Aruba': ['hpe', 'logo', 'networks'],
  'Ascend': ['arrange', 'arrow', 'sort', 'up'],
  'AssistListening': ['accessibility', 'audio', 'ear', 'hear', 'sound'],
  'Atm': ['bank', 'card', 'credit', 'cash', 'money'],
  'Attachment': ['clip', 'file', 'paper', 'paperclip'],
  'Attraction': ['amusement', 'carnival', 'circus', 'festival', 'tent'],
  'Baby': ['child', 'diaper', 'kid', 'newborn'],
  'BackTen': ['arrow', 'backward', 'rewind', 'seconds'],
  'Bar': ['beer', 'cocktail', 'drink', 'glass', 'party'],
  'BarChart': ['analytics', 'business', 'chart', 'graph', 'diagram'],
  'Basket': ['buy', 'carton', 'picnic', 'shopping'],
  'Bike': ['bicycle', 'cycle', 'transport'],
  'Bitcoin': ['coin', 'currency', 'finance', 'social', 'pay', 'money', 'wallet'],
  'Blog': ['article','news', 'feed', 'web'],
  'Book': ['education', 'learning', 'reading', 'study'],
  'BusinessService': ['cloud', 'webservice'],
  'Cafeteria': ['cafe', 'dining', 'food', 'fork', 'meal', 'restaurant', 'silverware', 'spoon'],
  'Calculator': ['adding machine', 'accounting', 'math'],
  'Calendar': ['date', 'day', 'event', 'schedule', 'month'],
  'Camera': ['image', 'lens', 'photo', 'photograpy', 'picture', 'shot'],
  'Capacity': ['bars'],
  'Car': ['auto', 'transport', 'vehicle'],
  'CaretDown': ['arrow', 'core', 'direction', 'down', 'expand'],
  'CaretNext': ['arrow', 'core', 'direction', 'forward', 'right'],
  'CaretPrevious': ['arrow', 'core', 'direction', 'rewind', 'left'],
  'CaretUp': ['arrow', 'collapse', 'core', 'direction', 'up'],
  'Cart': ['buy', 'ecommerce', 'shopping'],
  'Catalog': ['catalogue', 'book', 'directory', 'document', 'index'],
  'CatalogOption': ['catalogue', 'book', 'directory', 'document', 'index'],
  'Centos': ['linux', 'logo', 'os'],
  'Channel': ['communications', 'media', 'network', 'tv', 'television'],
  'ChapterAdd': ['add', 'create', 'new', 'plus'],
  'ChapterNext': ['arrow', 'forward'],
  'ChapterPrevious': ['arrow', 'backward'],
  'Chat': ['bubble', 'conversation', 'communication', 'core', 'help', 'message', 'talk', 'support'],
  'ChatOption': ['bubble', 'conversation', 'communication', 'core', 'help', 'message', 'talk', 'support'],
  'Checkbox': ['mark', 'tick'],
  'CheckboxSelected': ['mark', 'tick'],
  'Checkmark': ['accept', 'agree', 'core', 'done', 'good', 'ok'],
  'Chrome': ['browser', 'google', 'logo', 'web'],
  'CircleInformation': ['document', 'faq', 'help'],
  'CirclePlay': ['music', 'video'],
  'CircleQuestion': ['faq', 'help', 'support'],
  'Clear': ['forbidden', 'no', 'prohibited', 'stop'],
  'ClearOption': ['paintbrush'],
  'Cli': ['dos', 'line', 'command', 'console'],
  'Clipboard': ['document', 'list', 'report'],
  'Close': ['cancel', 'core', 'delete', 'escape', 'exit', 'remove', 'trash'],
  'ClosedCaption': ['accessibility'],
  'Cloud': ['computing', 'data', 'network', 'storage', 'weather'],
  'CloudComputer': ['computing', 'data', 'network', 'storage'],
  'CloudDownload': ['arrow', 'computing', 'data', 'network', 'storage'],
  'CloudSoftware': ['application', 'computing', 'data', 'network', 'storage'],
  'CloudUpload': ['arrow', 'backup', 'computing', 'data', 'hosting', 'network', 'save', 'storage'],
  'Cloudlinux': ['hosting', 'logo', 'os'],
  'Cluster': ['interconnect', 'map', 'network'],
  'CoatCheck': ['clothes', 'hanger', 'hotel'],
  'Code': ['application', 'coding', 'development', 'programming', 'web'],
  'Codepen': ['codepen.io', 'code', 'demo', 'logo', 'media', 'share', 'social'],
  'Columns': ['chart', 'graph', 'layout', 'table'],
  'Compare': ['ab', 'a/b', 'analysis', 'balance', 'testing', 'variations'],
  'Compass': ['direction', 'location', 'map', 'navigation', 'tool'],
  'Compliance': ['checklist', 'clipboard', 'mark', 'protection'],
  'Configure': ['core', 'preferences', 'setting', 'settings', 'tool', 'wrench'],
  'Connect': ['network', 'plug'],
  'Connectivity': ['network', 'plug'],
  'Contact': ['bubble', 'ellipses'],
  'ContactInfo': ['avatar', 'icommunication', 'phone', 'profile'],
  'Contract': ['arrow', 'exit fullscreen', 'minimize'],
  'Copy': ['documents', 'duplicate', 'file', 'paste'],
  'CreativeCommons': ['creative commons', 'license', 'social'],
  'CreditCard': ['amex', 'atm', 'debit', 'mastercard', 'visa', 'wallet'],
  'Css3': ['code', 'logo', 'stylesheet'],
  'Cube': ['3d', 'box', 'container', 'database', 'package'],
  'Cubes': ['3d', 'box', 'container', 'database', 'package'],
  'Currency': ['cash', 'dollar', 'finance', 'payment', 'money'],
  'Cursor': ['arrow', 'click', 'mouse', 'pointer'],
  'Cut': ['scissors', 'tool'],
  'Cycle': ['arrow', 'recycle', 'refresh', 'repeat'],
  'Document': ['core', 'file', 'format', 'folder', 'page', 'paper'],
  'Download': ['arrow', 'cloud', 'core', 'import', 'get', 'receive'],
  'Dropbox': ['box', 'cloud', 'logo', 'media', 'share', 'social'],
  'Edit': ['change', 'core', 'draw', 'modify', 'pen', 'pencil', 'write'],
  'Facebook': ['share', 'logo', 'media', 'network', 'social'],
  'FacebookOption': ['share', 'logo', 'media', 'network', 'social'],
  'Filter': ['core', 'funnel', 'refine', 'sort', 'triage'],
  'Flag': ['core', 'nation', 'warn', 'warning'],
  'FormAdd': ['create', 'form', 'increase', 'increment', 'new', 'plus'],
  'formAttachment': ['attach', 'clip', 'file', 'form', 'paper', 'upload'],
  'FormCalendar': ['date', 'day', 'event', 'form', 'month', 'schedule', 'year'],
  'FormClock': ['alarm', 'form', 'hour', 'minute', 'second', 'time', 'timer', 'watch'],
  'FormClose': ['cancel', 'close', 'delete', 'escape', 'exit', 'form', 'remove', 'trash'],
  'FormCheckmark': ['accept', 'agree', 'done', 'form', 'good', 'ok'],
  'FormCut': ['scissors', 'form', 'tool'],
  'FormDown': ['arrow', 'direction', 'form', 'down', 'expand', 'up'],
  'FormFilter': ['form', 'funnel', 'refine', 'sort', 'triage'],
  'FormFolder': ['file', 'files', 'document', 'form', 'organize'],
  'FormLocation': ['directions', 'form', 'gps', 'map', 'navigation', 'pin'],
  'FormLock': ['form', 'locker', 'password', 'permissions', 'protection', 'secure', 'security'],
  'FormNext': ['arrow', 'direction', 'form', 'forward', 'next', 'right'],
  'FormNextLink': ['arrow', 'direction', 'form', 'forward', 'next', 'right'],
  'FormPrevious': ['arrow', 'back', 'backward', 'direction', 'form', 'left', 'return'],
  'FormPreviousLink': ['arrow', 'back', 'backward', 'direction', 'form', 'left', 'return'],
  'FormRefresh': ['arrow', 'form', 'pull', 'reload', 'sync', 'update'],
  'FormSearch': ['find', 'form', 'lookup', 'magnifier', 'search'],
  'FormSchedule': ['appointment', 'calendar', 'date', 'event', 'form', 'meeting', 'time'],
  'FormSubtract': ['decrement', 'delete', 'form', 'minus', 'reduce', 'remove'],
  'FormTrash': ['bin', 'clear', 'core', 'delete', 'eliminate', 'escape', 'form', 'garbage', 'remove'],
  'FormUp': ['arrow', 'direction', 'collapse', 'form', 'up'],
  'FormUpload': ['arrow', 'attach', 'attachment', 'cloud', 'export', 'file', 'form', 'send'],
  'FormView': ['eye', 'form', 'open'],
  'FormViewHide': ['close', 'eye', 'form'],
  'Github': ['code', 'demo', 'logo', 'media', 'share', 'social', 'opensource'],
  'GooglePlus': ['logo', 'media', 'share', 'social'],
  'GoogleWallet': ['logo', 'media', 'online', 'pay', 'social', 'transaction', 'wallet'],
  'Instagram': ['camera', 'image', 'logo', 'media', 'picture', 'photo', 'share', 'social', 'video'],
  'Linkedin': ['logo', 'network', 'media', 'share', 'social'],
  'LinkedinOption': ['logo', 'network', 'media', 'share', 'social'],
  'LinkNext': ['arrow', 'core', 'direction', 'forward', 'next', 'right'],
  'LinkPrevious': ['arrow', 'back', 'backward', 'core', 'direction', 'left', 'return'],
  'Mail': ['email', 'envelope', 'letter', 'message', 'social'],
  'Mastercard': ['card', 'credit', 'logo', 'pay', 'wallet', 'social', 'visa'],
  'Medium': ['blog', 'logo', 'media', 'share', 'social'],
  'More': ['actions', 'core', 'ellipses'],
  'Next': ['arrow', 'core', 'direction', 'forward', 'next', 'right'],
  'Notification': ['alarm', 'alert', 'bell', 'core', 'message', 'notify', 'warn', 'warning'],
  'Paypal': ['card', 'logo', 'media', 'money', 'social', 'pay', 'wallet'],
  'Pinterest': ['logo', 'media', 'share', 'social'],
  'Previous': ['arrow', 'back', 'backward', 'core', 'direction', 'left', 'return'],
  'Product-hunt': ['logo', 'media', 'share', 'social'],
  'Reddit': ['logo', 'media', 'online', 'social', 'share'],
  'Refresh': ['arrow', 'core', 'reload', 'pull', 'sync', 'update'],
  'Search': ['core', 'find', 'lookup', 'magnifier', 'zoom'],
  'Share': ['connections', 'score', 'open', 'network', 'publish'],
  'Skype': ['call', 'chat', 'conference', 'logo', 'media', 'phone', 'social', 'video'],
  'Slack': ['chat', 'help', 'logo', 'media', 'message', 'talk', 'share', 'social', 'support'],
  'Snapchat': ['ghost', 'image', 'logo', 'media', 'picture', 'photo', 'share', 'social', 'video'],
  'Square': ['logo', 'media', 'social', 'pay', 'wallet'],
  'StackOverflow': ['code', 'help', 'logo', 'media', 'share', 'social'],
  'Stripe': ['logo', 'media', 'pay', 'social', 'wallet'],
  'Subtract': ['core', 'decrement', 'minus', 'reduce'],
  'Twitter': ['bird', 'logo', 'media', 'share', 'social', 'tweet'],
  'Trash': ['bin', 'clear', 'core', 'delete', 'eliminate', 'escape', 'garbage', 'remove'],
  'Tumblr': ['blog', 'image', 'logo', 'media', 'picture', 'photo', 'share', 'social', 'video'],
  'Update': ['arrow', 'change', 'core', 'reload', 'refresh'],
  'Upload': ['arrow', 'attach', 'attachment', 'cloud', 'core', 'export', 'file', 'send'],
  'User': ['account', 'avatar', 'core', 'person', 'profile'],
  'Vimeo': ['logo', 'media', 'share', 'social', 'video'],
  'Visa': ['amex', 'card', 'credit', 'mastercard', 'media', 'pay', 'social', 'wallet'],
  'Youtube': ['logo', 'media', 'play', 'share', 'social', 'video'],
  'Wordpress': ['blog', 'logo', 'media', 'share', 'social'],
};
