export default {
  'Accessibility': ['body', 'disabled', 'disability', 'human'],
  'Achievement': ['award', 'medal', 'prize', 'winner'],
  'Action': ['connect', 'plug'],
  'Actions': ['gear', 'sun'],
  'Ad': ['advertising', 'marketing', 'promotion'],
  'Add': ['create', 'core', 'increase', 'increment', 'new', 'plus'],
  'AddCircle': ['create', 'increase', 'increment', 'new', 'plus'],
  'Aed': ['cpr', 'defibrillator', 'emergency', 'heart', 'medical', 'shock'],
  'Aggregate': ['add', 'combinatin', 'combine', 'join', 'merge'],
  'Aid': ['briefcase', 'care', 'emergency', 'first-aid', 'first aid kit', 'health', 'hospital'],
  'AidOption': ['briefcase', 'care', 'emergency', 'first-aid', 'first aid kit', 'health', 'hospital'],
  'Alarm': ['alert', 'alarmclock', 'bell', 'clock', 'time', 'timer'],
  'Alert': ['alarm', 'attention', 'error', 'important', 'warning'],
  'Amazon': ['buy', 'marketplace', 'online', 'shopping', 'social'],
  'Amex': ['atm', 'card', 'credit', 'pay', 'wallet', 'social'],
  'Analytics': ['chart', 'diagram', 'dontusepies', 'graph', 'pie', 'report', 'statistics'],
  'Android': ['cyborg', 'droid', 'humanoid', 'mobile', 'os', 'phone', 'robot', 'smartphone'],
  'Announce': ['bullhorn', 'loud', 'speaker', 'megaphone'],
  'Apple': ['donglebook', 'iphone', 'imac', 'logo', 'mac', 'macbook'],
  'Archive': ['box', 'container', 'document', 'files', 'folder', 'storage'],
  'Archlinux': ['linux', 'logo', 'os'],
  'Article': ['blog', 'news', 'newspaper', 'press'],
  'Aruba': ['hpe', 'logo', 'networks'],
  'Ascend': ['arrange', 'arrow', 'sort', 'up'],
  'AssistListening': ['accessibility', 'audio', 'ear', 'hear', 'sound'],
  'Atm': ['bank', 'card', 'credit', 'cash', 'finance', 'money'],
  'Attachment': ['clip', 'files', 'paper', 'paperclip'],
  'Attraction': ['amusement', 'carnival', 'circus', 'festival', 'tent'],
  'Baby': ['child', 'diaper', 'kid', 'newborn'],
  'BackTen': ['arrow', 'backward', 'rewind', 'seconds'],
  'Bar': ['beer', 'cocktail', 'drink', 'glass', 'party'],
  'BarChart': ['analytics', 'business', 'chart', 'graph', 'diagram'],
  'Basket': ['buy', 'carton', 'picnic', 'shopping'],
  'Bike': ['bicycle', 'cycle', 'transport'],
  'Bitcoin': ['coin', 'currency', 'finance', 'social', 'pay', 'money', 'wallet'],
  'Blog': ['article', 'news', 'feed', 'web'],
  'Book': ['education', 'learning', 'reading', 'study'],
  'BusinessService': ['cloud', 'webservice'],
  'Cafeteria': ['cafe', 'dining', 'food', 'fork', 'meal', 'restaurant', 'silverware', 'spoon'],
  'Calculator': ['adding machine', 'accounting', 'math'],
  'Calendar': ['date', 'day', 'event', 'schedule', 'month'],
  'Camera': ['image', 'lens', 'photos', 'photograpy', 'picture', 'shot'],
  'Capacity': ['bars'],
  'Car': ['auto', 'transport', 'vehicle'],
  'CaretDown': ['arrow', 'core', 'direction', 'down', 'expand'],
  'CaretNext': ['arrow', 'core', 'direction', 'forward', 'right'],
  'CaretPrevious': ['arrow', 'core', 'direction', 'rewind', 'left'],
  'CaretUp': ['arrow', 'collapse', 'core', 'direction', 'up'],
  'Cart': ['buy', 'ecommerce', 'shopping'],
  'Catalog': ['catalogue', 'book', 'directory', 'document', 'index'],
  'CatalogOption': ['catalogue', 'book', 'directory', 'document', 'index'],
  'Centos': ['linux', 'logo', 'os'],
  'Channel': ['communications', 'media', 'network', 'tv', 'television'],
  'ChapterAdd': ['add', 'create', 'new', 'plus'],
  'ChapterNext': ['arrow', 'forward'],
  'ChapterPrevious': ['arrow', 'backward'],
  'Chat': ['bubble', 'conversation', 'communication', 'core', 'help', 'message', 'talk', 'support'],
  'ChatOption': ['bubble', 'conversation', 'communication', 'core', 'help', 'message', 'talk', 'support'],
  'Checkbox': ['mark', 'tick'],
  'CheckboxSelected': ['mark', 'tick'],
  'Checkmark': ['accept', 'agree', 'core', 'done', 'good', 'ok'],
  'Chrome': ['browser', 'google', 'logo', 'web'],
  'CircleInformation': ['document', 'faq', 'help'],
  'CirclePlay': ['music', 'video'],
  'CircleQuestion': ['faq', 'help', 'support'],
  'Clear': ['forbidden', 'no', 'prohibited', 'stop'],
  'ClearOption': ['paintbrush'],
  'Cli': ['dos', 'line', 'command', 'console'],
  'Clipboard': ['document', 'list', 'report'],
  'Close': ['cancel', 'core', 'delete', 'escape', 'exit', 'remove', 'trash'],
  'ClosedCaption': ['accessibility'],
  'Cloud': ['computing', 'data', 'network', 'storage', 'weather'],
  'CloudComputer': ['computing', 'data', 'network', 'storage'],
  'CloudDownload': ['arrow', 'computing', 'data', 'network', 'storage'],
  'CloudSoftware': ['application', 'computing', 'data', 'network', 'storage'],
  'CloudUpload': ['arrow', 'backup', 'computing', 'data', 'hosting', 'network', 'save', 'storage'],
  'Cloudlinux': ['hosting', 'logo', 'os'],
  'Cluster': ['interconnect', 'map', 'network'],
  'CoatCheck': ['clothes', 'hanger', 'hotel'],
  'Code': ['application', 'coding', 'development', 'programming', 'web'],
  'Codepen': ['codepen.io', 'code', 'demo', 'logo', 'media', 'share', 'social'],
  'Columns': ['chart', 'graph', 'layout', 'table'],
  'Compare': ['ab', 'a/b', 'analytics', 'balance', 'testing', 'variations'],
  'Compass': ['direction', 'location', 'map', 'navigation', 'tool'],
  'Compliance': ['checklist', 'clipboard', 'mark', 'protection'],
  'Configure': ['core', 'preferences', 'setting', 'settings', 'tool', 'wrench'],
  'Connect': ['network', 'plug'],
  'Connectivity': ['network', 'plug'],
  'Contact': ['bubble', 'ellipses'],
  'ContactInfo': ['avatar', 'icommunication', 'phone', 'profile'],
  'Contract': ['arrow', 'exit fullscreen', 'minimize'],
  'Copy': ['documents', 'duplicate', 'files', 'paste'],
  'CreativeCommons': ['creative commons', 'license', 'social'],
  'CreditCard': ['amex', 'atm', 'debit', 'mastercard', 'visa', 'wallet'],
  'Css3': ['code', 'coding', 'logo', 'stylesheet'],
  'Cube': ['3d', 'box', 'container', 'database', 'package'],
  'Cubes': ['3d', 'box', 'container', 'database', 'package'],
  'Currency': ['cash', 'dollar', 'finance', 'payment', 'money'],
  'Cursor': ['arrow', 'click', 'mouse', 'pointer'],
  'Cut': ['scissors', 'tool'],
  'Cycle': ['arrow', 'recycle', 'refresh', 'repeat'],
  'Dashboard': ['guage', 'speedometer'],
  'Database': ['rack', 'server', 'storage'],
  'Debian': ['logo', 'os'],
  'Deliver': ['delivery', 'shipping', 'transport', 'truck'],
  'Deploy': ['rocket', 'spaceship'],
  'Descend': ['arrow', 'downward', 'sort'],
  'Desktop': ['computer', 'display', 'monitor', 'pc', 'screen'],
  'Detach': ['cut', 'paperclip', 'remove'],
  'Device': ['iot', 'technology', 'tv'],
  'Diamond': ['gem', 'jewelry', 'stone'],
  'Directions': ['arrow', 'location', 'navigation'],
  'Dislike': ['thumbs', 'down', 'like'],
  'Docker': ['app', 'container', 'logo', 'media', 'social'],
  'Document': ['core', 'files', 'format', 'folder', 'page', 'paper'],
  'DocumentCloud': ['cloud', 'files', 'folder', 'page', 'paper'],
  'DocumentCsv': ['extension', 'files', 'format', 'folder', 'page', 'paper'],
  'DocumentDownload': ['arrow', 'files', 'import', 'get', 'page', 'paper', 'receive'],
  'DocumentExcel': ['extension', 'files', 'format', 'folder', 'microsoft', 'office', 'page', 'paper', 'xls'],
  'DocumentImage': ['files', 'folder', 'page', 'paper', 'photography', 'photos', 'picture'],
  'DocumentLocked': ['files', 'folder', 'page', 'paper', 'password', 'secure', 'security'],
  'DocumentMissing': ['delete', 'error', 'files', 'folder', 'page', 'paper', 'remove'],
  'DocumentNotes': ['extension', 'files', 'folder', 'page', 'paper'],
  'DocumentOutlook': ['extension', 'files', 'folder', 'microsoft', 'office', 'page', 'paper'],
  'DocumentPdf': ['extension', 'files', 'folder', 'format', 'page', 'paper'],
  'DocumentPerformance': ['arrow', 'files', 'folder', 'format', 'page', 'paper'],
  'DocumentPpt': ['extension', 'files', 'folder', 'microsoft', 'office', 'page', 'paper', 'powerpoint'],
  'DocumentRtf': ['extension', 'files', 'folder', 'format', 'page', 'paper'],
  'DocumentSound': ['audio', 'files', 'folder', 'music', 'page', 'paper'],
  'DocumentStore': ['data', 'files', 'folder', 'page', 'paper'],
  'DocumentTest': ['files', 'flask', 'folder', 'page', 'paper'],
  'DocumentText': ['extension', 'files', 'folder', 'format', 'page', 'paper'],
  'DocumentThreat': ['bomb', 'danger', 'files', 'folder', 'malware', 'page', 'paper', 'virus'],
  'DocumentTime': ['alarm', 'clock', 'event', 'files', 'folder', 'page', 'paper'],
  'DocumentTransfer': ['arrow', 'files', 'folder', 'page', 'paper'],
  'DocumentTxt': ['extension', 'files', 'folder', 'format', 'page', 'paper'],
  'DocumentUpdate': ['arrow', 'files', 'folder', 'page', 'paper', 'refresh'],
  'DocumentUpload': ['arrow', 'files', 'import', 'get', 'page', 'paper', 'send'],
  'DocumentUser': ['account', 'avatar', 'files', 'folder', 'page', 'paper', 'person', 'profile'],
  'DocumentVerified': ['check', 'files', 'folder', 'mark', 'page', 'paper'],
  'DocumentVideo': ['camera', 'files', 'folder', 'page', 'paper', 'video'],
  'DocumentExe': ['executable', 'extension', 'files', 'folder', 'page', 'paper'],
  'DocumentWord': ['extension', 'files', 'folder', 'microsoft', 'office', 'page', 'paper'],
  'DocumentZip': ['compressed', 'extension', 'files', 'folder', 'format', 'page', 'paper'],
  'Domain': ['internet', 'website', 'www'],
  'Dos': ['command', 'code', 'files', 'os'],
  'Down': ['arrow', 'expand', 'drop'],
  'Download': ['arrow', 'cloud', 'core', 'import', 'get', 'receive'],
  'Drag': ['drop'],
  'DriveCage': ['data', 'disk', 'rack', 'storage'],
  'Dropbox': ['box', 'cloud', 'logo', 'media', 'share', 'social'],
  'Duplicate': ['add', 'copy'],
  'Dxc': ['awesome', 'logo'],
  'Edge': ['browser', 'logo', 'microsoft', 'web'],
  'Edit': ['change', 'core', 'draw', 'modify', 'pen', 'pencil', 'write'],
  'Eject': ['control', 'media', 'player'],
  'Elevator': ['down', 'lift', 'up', 'transport'],
  'Emergency': ['alert', 'asterisk'],
  'EmptyCircle': ['chart', 'donut'],
  'Erase': ['delete', 'eraser', 'remove'],
  'Escalator': ['stairs', 'staircase', 'moving', 'up'],
  'Expand': ['arrow', 'direction', 'maximize', 'full', 'screen'],
  'Facebook': ['share', 'logo', 'media', 'network', 'social'],
  'FacebookOption': ['share', 'logo', 'media', 'network', 'social'],
  'Fan': ['air', 'cooling', 'ventilator'],
  'FastForward': ['arrow', 'next', 'player', 'right'],
  'Favorite': ['heart', 'like'],
  'Fedora': ['logo', 'os'],
  'Filter': ['core', 'funnel', 'refine', 'sort', 'triage'],
  'FingerPrint': ['security', 'biometric', 'scan'],
  'Fireball': ['star'],
  'Firefox': ['browser', 'logo', 'web'],
  'Flag': ['core', 'nation', 'warn', 'warning'],
  'Folder': ['documents', 'data', 'files'],
  'FolderCycle': ['documents', 'data', 'files', 'recycle', 'refresh'],
  'FolderOpen': ['documents', 'data', 'files'],
  'FormAdd': ['create', 'form', 'increase', 'increment', 'new', 'plus'],
  'formAttachment': ['attach', 'clip', 'files', 'form', 'paper', 'upload'],
  'FormCalendar': ['date', 'day', 'event', 'form', 'month', 'schedule', 'year'],
  'FormCheckmark': ['accept', 'agree', 'done', 'form', 'good', 'ok'],
  'FormClock': ['alarm', 'form', 'hour', 'minute', 'second', 'time', 'timer', 'watch'],
  'FormClose': ['cancel', 'close', 'delete', 'escape', 'exit', 'form', 'remove', 'trash'],
  'FormCut': ['scissors', 'form', 'tool'],
  'FormDown': ['arrow', 'direction', 'form', 'down', 'expand', 'up'],
  'FormFilter': ['form', 'funnel', 'refine', 'sort', 'triage'],
  'FormFolder': ['files', 'document', 'form', 'organize'],
  'FormLocation': ['directions', 'form', 'gps', 'map', 'navigation', 'pin'],
  'FormLock': ['form', 'locker', 'password', 'permissions', 'protection', 'secure', 'security'],
  'FormNext': ['arrow', 'direction', 'form', 'forward', 'next', 'right'],
  'FormNextLink': ['arrow', 'direction', 'form', 'forward', 'next', 'right'],
  'FormPrevious': ['arrow', 'back', 'backward', 'direction', 'form', 'left', 'return'],
  'FormPreviousLink': ['arrow', 'back', 'backward', 'direction', 'form', 'left', 'return'],
  'FormRefresh': ['arrow', 'form', 'pull', 'reload', 'sync', 'update'],
  'FormSchedule': ['appointment', 'calendar', 'date', 'event', 'form', 'meeting', 'time'],
  'FormSearch': ['find', 'form', 'lookup', 'magnifier', 'search'],
  'FormSubtract': ['decrement', 'delete', 'form', 'minus', 'reduce', 'remove'],
  'FormTrash': ['bin', 'clear', 'core', 'delete', 'eliminate', 'escape', 'form', 'garbage', 'remove'],
  'FormUp': ['arrow', 'direction', 'collapse', 'form', 'up'],
  'FormUpload': ['arrow', 'attach', 'attachment', 'cloud', 'export', 'files', 'form', 'send'],
  'FormView': ['eye', 'form', 'open'],
  'FormViewHide': ['close', 'eye', 'form'],
  'Gallery': ['image', 'pictures', 'photography', 'photos'],
  'Gamepad': ['joystick', 'play', 'sports'],
  'Gift': ['birthday', 'box', 'christmas', 'present'],
  'Github': ['code', 'demo', 'logo', 'media', 'share', 'social', 'opensource'],
  'Globe': ['earth', 'global', 'internet', 'planet', 'world'],
  'Golang': ['code', 'google', 'logo'],
  'Google': ['logo', 'search'],
  'GooglePlus': ['logo', 'media', 'share', 'social'],
  'GoogleWallet': ['logo', 'media', 'online', 'pay', 'social', 'transaction', 'wallet'],
  'Gremlin': ['awesome', 'grommet'],
  'Grid': ['line', 'layout'],
  'Grommet': ['awesome', 'logo'],
  'Group': ['people', 'team', 'users'],
  'Grow': ['growth', 'plant'],
  'Hadoop': ['big', 'database', 'logo'],
  'Halt': ['hand', 'sign', 'stop'],
  'Help': ['information', 'service', 'support', 'question'],
  'Heroku': ['cloud', 'deployment', 'logo', 'paas'],
  'History': ['clock', 'timer', 'schedule'],
  'Home': ['building', 'estate', 'house', 'real'],
  'Horton': ['big', 'data', 'logo'],
  'Host': ['database', 'hosting', 'rack', 'server'],
  'HostMaintenance': ['hosting', 'rack', 'server', 'service', 'settings', 'repair'],
  'Hp': ['awesome', 'hewlett', 'logo', 'packard'],
  'Hpe': ['awesome', 'enterprise', 'hewlett', 'logo', 'packard'],
  'HpeLabs': ['awesome', 'enterprise', 'hewlett', 'logo', 'packard'],
  'Hpi': ['awesome', 'hewlett', 'logo', 'packard'],
  'Html5': ['code', 'coding', 'web'],
  'IceCream': ['dessert', 'food'],
  'Image': ['photography', 'photos', 'picture'],
  'Impact': ['crash', 'explode'],
  'InProgress': ['clock', 'hourglass', 'timer'],
  'Inbox': ['email', 'message', 'letter', 'tray'],
  'Indicator': ['location', 'marker', 'pin'],
  'Info': ['bulb', 'data', 'help', 'idea', 'information', 'light', 'support'],
  'Inherit': ['family', 'pedigree', 'tree'],
  'Inspect': ['eye', 'glasses', 'spectacles'],
  'Instagram': ['camera', 'image', 'logo', 'media', 'picture', 'photography', 'photos', 'share', 'social', 'video'],
  'Install': ['configuration', 'download', 'settings', 'setup'],
  'InstallOption': ['arrow', 'configuration', 'download', 'settings', 'setup'],
  'Integration': ['connection', 'plug', 'system'],
  'InternetExplorer': ['browser', 'logo', 'web'],
  'Iteration': ['iterate', 'repeat', 'stack', 'steps'],
  'Java': ['coffee', 'code', 'coding', 'cup'],
  'Language': ['earth', 'internet', 'translate', 'world'],
  'Launch': ['rocket', 'spaceship', 'startup'],
  'Layer': ['arrange', 'layers', 'stack'],
  'License': ['key', 'lock'],
  'Like': ['favorite', 'heart', 'thumbs', 'up'],
  'LineChart': ['graph', 'grow', 'time'],
  'Link': ['chain', 'connection', 'network', 'web'],
  'LinkBottom': ['align', 'arrow', 'direction', 'down'],
  'LinkDown': ['arrow', 'direction', 'down'],
  'LinkNext': ['arrow', 'core', 'direction', 'forward', 'next', 'right'],
  'LinkPrevious': ['arrow', 'back', 'backward', 'core', 'direction', 'left', 'return'],
  'LinkTop': ['arrow', 'direction', 'up'],
  'LinkUp': ['arrow', 'direction', 'up'],
  'Linkedin': ['logo', 'network', 'media', 'share', 'social'],
  'LinkedinOption': ['logo', 'network', 'media', 'share', 'social'],
  'Local': ['flag', 'language', 'location', 'usa'],
  'Location': ['gps', 'map', 'navigation', 'pin'],
  'LocationPin': ['gps', 'map', 'navigation', 'pin'],
  'Lock': ['key', 'password', 'protectio', 'secure', 'security'],
  'Login': ['account', 'arrow', 'door', 'password', 'security'],
  'Logout': ['account', 'arrow', 'door', 'exit', 'password', 'security'],
  'Lounge': ['chair', 'furniture', 'sofa'],
  'Magic': ['wand', 'wizard'],
  'Mail': ['email', 'envelope', 'letter', 'message', 'social'],
  'MailOption': ['email', 'envelope', 'letter', 'message', 'social'],
  'Mandriva': ['linux', 'logo', 'os'],
  'Manual': ['stick', 'joystick'],
  'Map': ['gps', 'location', 'navigation', 'pin'],
  'MapLocation': ['gps', 'location', 'navigation', 'pin'],
  'Mastercard': ['card', 'credit', 'logo', 'pay', 'wallet', 'social', 'visa'],
  'Medium': ['blog', 'logo', 'media', 'share', 'social'],
  'Menu': ['hamburger', 'list', 'navigation', 'options'],
  'Microfocus': ['awesome', 'logo'],
  'Microphone': ['audio', 'mic', 'music', 'sound'],
  'Money': ['cash', 'coins', 'currency', 'dollar', 'finance'],
  'Monitor': ['computer', 'crt', 'desktop', 'display', 'screen'],
  'More': ['actions', 'core', 'ellipses'],
  'Multimedia': ['clapboard', 'cinema', 'film', 'video', 'movie'],
  'Multiple': ['repeat', 'stack', 'steps'],
  'Music': ['audio', 'notes', 'sound', 'play'],
  'Mysql': ['database', 'logo', 'storage'],
  'Navigate': ['guide', 'road', 'sign', 'street', 'way'],
  'New': ['asterisk', 'add', 'create', 'plus'],
  'NewWindow': ['add', 'create', 'plus'],
  'Next': ['arrow', 'core', 'direction', 'forward', 'next', 'right'],
  'Nodes': ['connection', 'network'],
  'Norton': ['logo', 'security'],
  'Note': ['document', 'file', 'paper'],
  'Notes': ['document', 'file', 'paper'],
  'Notification': ['alarm', 'alert', 'bell', 'core', 'message', 'notify', 'warn', 'warning'],
  'ObjectGroup': [''],
  'ObjectUngroup': [''],
  'OfflineStorage': ['backup', 'tape'],
  'Onedrive': ['logo', 'office'],
  'Opera': ['browser', 'logo', 'web'],
  'Optimize': ['analytics', 'chart', 'growth'],
  'Oracle': ['cloud', 'database', 'logo'],
  'Organization': ['building'],
  'Overview': ['binoculars'],
  'Paint': ['bucket', 'color'],
  'Pan': ['arrow', 'drag', 'move'],
  'Pause': ['player'],
  'PauseFill': ['player'],
  'Paypal': ['card', 'logo', 'media', 'money', 'social', 'pay', 'wallet'],
  'Performance': ['optimization'],
  'PersonalComputer': ['pc', 'monitor', 'screen'],
  'PieChart': ['analytics', 'dontusepies', 'graph'],
  'Pin': ['gps', 'location', 'map', 'navigation', 'pin', 'tack'],
  'Pinterest': ['logo', 'media', 'share', 'social'],
  'Plan': ['calendar', 'checklist', 'schedule'],
  'Play': ['media', 'music', 'player', 'video'],
  'PlayFill': ['media', 'music', 'player', 'video'],
  'Power': ['off', 'switch'],
  'Previous': ['arrow', 'back', 'backward', 'core', 'direction', 'left', 'return'],
  'Print': ['laser', 'printer'],
  'ProductHunt': ['logo', 'media', 'share', 'social'],
  'Reddit': ['logo', 'media', 'online', 'social', 'share'],
  'Refresh': ['arrow', 'core', 'reload', 'pull', 'sync', 'update'],
  'Search': ['core', 'find', 'lookup', 'magnifier', 'zoom'],
  'Share': ['connections', 'score', 'open', 'network', 'publish'],
  'Skype': ['call', 'chat', 'conference', 'logo', 'media', 'phone', 'social', 'video'],
  'Slack': ['chat', 'help', 'logo', 'media', 'message', 'talk', 'share', 'social', 'support'],
  'Snapchat': ['ghost', 'image', 'logo', 'media', 'picture', 'photography', 'photos', 'share', 'social', 'video'],
  'Square': ['logo', 'media', 'social', 'pay', 'wallet'],
  'StackOverflow': ['code', 'help', 'logo', 'media', 'share', 'social'],
  'Stripe': ['logo', 'media', 'pay', 'social', 'wallet'],
  'Subtract': ['core', 'decrement', 'minus', 'reduce'],
  'Twitter': ['bird', 'logo', 'media', 'share', 'social', 'tweet'],
  'Trash': ['bin', 'clear', 'core', 'delete', 'eliminate', 'escape', 'garbage', 'remove'],
  'Tumblr': ['blog', 'image', 'logo', 'media', 'picture', 'photography', 'photos', 'share', 'social', 'video'],
  'Update': ['arrow', 'change', 'core', 'reload', 'refresh'],
  'Upload': ['arrow', 'attach', 'attachment', 'cloud', 'core', 'export', 'files', 'send'],
  'User': ['account', 'avatar', 'core', 'person', 'profile'],
  'Vimeo': ['logo', 'media', 'share', 'social', 'video'],
  'Visa': ['amex', 'card', 'credit', 'mastercard', 'media', 'pay', 'social', 'wallet'],
  'Youtube': ['logo', 'media', 'play', 'share', 'social', 'video'],
  'Wordpress': ['blog', 'logo', 'media', 'share', 'social']
};