export default {
  'Add': ['create', 'core', 'increase', 'increment', 'plus'],
  'Amazon': ['buy', 'marketplace', 'social'],
  'AmericanExpress': ['card', 'pay', 'wallet', 'social'],
  'Bitcoin': ['social', 'pay', 'wallet'],
  'CarrotDown': ['core', 'down', 'expand'],
  'CarrotUp': ['collapse', 'core', 'up'],
  'Chat': ['core', 'help', 'message', 'talk', 'support'],
  'Checkmark': ['accept', 'agree', 'core', 'good', 'ok'],
  'Close': ['core', 'delete', 'escape', 'remove', 'trash'],
  'Codepen': ['code', 'demo', 'share', 'social'],
  'Configure': ['core', 'preferences', 'settings', 'tool'],
  'CreativeCommons': ['license', 'social'],
  'Document': ['core', 'file', 'page'],
  'Download': ['core', 'import', 'get', 'receive'],
  'Dropbox': ['cloud', 'share', 'social'],
  'Edit': ['change', 'core', 'draw', 'modify', 'pencil'],
  'Facebook': ['share', 'social'],
  'FacebookOption': ['share', 'social'],
  'Filter': ['core', 'funnel', 'refine', 'triage'],
  'Flag': ['core', 'warn', 'warning'],
  'FormAdd': ['create', 'form', 'increase', 'increment', 'plus'],
  'formAttachment': ['attach', 'clip', 'form', 'upload'],
  'FormCalendar': ['date', 'day', 'form', 'month', 'year'],
  'FormClock': ['form', 'hour', 'minute', 'second', 'time', 'watch'],
  'FormClose': ['close', 'delete', 'escape', 'form', 'remove', 'trash'],
  'FormCheckmark': ['accept', 'agree', 'form', 'good', 'ok'],
  'FormCut': ['cisors', 'form'],
  'FormDowm': ['form', 'down', 'expand'],
  'FormFilter': ['form', 'funnel', 'refine', 'triage'],
  'FormFolder': ['form', 'organize'],
  'FormLocation': ['directions', 'form', 'pin'],
  'FormLock': ['form', 'locker', 'permissions', 'protect', 'secure'],
  'FormNext': ['form', 'forward', 'next', 'right'],
  'FormPrevious': ['back', 'backward', 'form', 'left', 'return'],
  'FormPreviousLink': ['back', 'backward', 'form', 'left', 'return'],
  'FormRefresh': ['form', 'pull', 'update'],
  'FormSearch': ['find', 'form', 'lookup', 'magnifier', 'search'],
  'FormSchedule': ['appointment', 'form', 'meeting'],
  'FormSubtract': ['decrement', 'form', 'menus', 'reduce'],
  'FormTrash': ['clear', 'core', 'delete', 'eliminate', 'escape', 'form', 'remove'],
  'FormUp': ['collapse', 'form', 'up'],
  'FormUpload': ['attach', 'attachment', 'export', 'form', 'send'],
  'FormView': ['eye', 'form', 'open'],
  'FormViewHide': ['close', 'eye', 'form'],
  'Github': ['code', 'demo', 'share', 'social', 'opensource'],
  'GooglePlus': ['share', 'social'],
  'GoogleWallet': ['social', 'pay', 'wallet'],
  'Instagram': ['image', 'picture', 'photo', 'share', 'social', 'video'],
  'Linkedin': ['share', 'social'],
  'LinkedinOption': ['share', 'social'],
  'LinkNext': ['arrow', 'core', 'forward', 'next', 'right'],
  'LinkPrevious': ['arrow', 'back', 'backward', 'core', 'left', 'return'],
  'Mail': ['email', 'message', 'social'],
  'Mastercard': ['card', 'pay', 'wallet', 'social'],
  'Medium': ['blog', 'share', 'social'],
  'More': ['actions', 'core'],
  'Next': ['core', 'forward', 'next', 'right'],
  'Notification': ['alert', 'bell', 'core', 'notify', 'warn', 'warning'],
  'Paypal': ['social', 'pay', 'wallet'],
  'Pinterest': ['share', 'social'],
  'Previous': ['back', 'backward', 'core', 'left', 'return'],
  'Product-hunt': ['share', 'social'],
  'Reddit': ['social', 'share'],
  'Refresh': ['core', 'pull', 'update'],
  'Search': ['core', 'find', 'lookup', 'magnifier'],
  'Share': ['core', 'open', 'publish'],
  'Skype': ['call', 'conference', 'phone', 'social', 'video'],
  'Slack': ['chat', 'help', 'message', 'talk', 'share', 'social', 'support'],
  'Snapchat': ['image', 'picture', 'photo', 'share', 'social', 'video'],
  'Square': ['social', 'pay', 'wallet'],
  'StackOverflow': ['code', 'help', 'share', 'social'],
  'Stripe': ['social', 'pay', 'wallet'],
  'Subtract': ['core', 'decrement', 'minus', 'reduce'],
  'Twitter': ['share', 'social', 'tweet'],
  'Trash': ['clear', 'core', 'delete', 'eliminate', 'escape', 'remove'],
  'Tumblr': ['blog', 'image', 'picture', 'photo', 'share', 'social', 'video'],
  'Update': ['change', 'core'],
  'Upload': ['attach', 'attachment', 'core', 'export', 'send'],
  'User': ['core', 'person', 'profile'],
  'Vimeo': ['share', 'social', 'video'],
  'Visa': ['card', 'pay', 'wallet', 'social'],
  'Youtube': ['share', 'social', 'video'],
  'Wordpress': ['blog', 'share', 'social']
};